### ISSUE TITLE
brew installation

### ISSUE THREAD

**Issue by bill209** [awslabs/git-secrets#11]
Hi Michael, first THANKS for providing this tool - i have installed it and it is working great. i am sure this will be an invaluable help to a lot of people.

I did want to mention that this tool was not found amongst the Brew packages, and is unable to be installed via Brew as directed. it did install perfectly fine, however, through the make install process.

i apologize if this is an inappropriate means to get this information to you - i was unaware of another way to contact you.  please feel free to close this out at your convenience.

thank you again!
bill

**Comment by manabusakai** [comment]
Hi bill.

Please tell me the version of your OS.
I was successfully installed. (OS X El Capitan 10.11.3)

```
$ brew update
$ brew install git-secrets
==> Downloading https://homebrew.bintray.com/bottles/git-secrets-1.0.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-secrets-1.0.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/git-secrets/1.0.1: 7 files, 51.8K
```

**Comment by bill209** [comment]
Manabu, my apologies. after doing a brew update (which i realize now i should ALWAYS do), and getting on another network, the brew install git-secrets worked just fine. thank you so much for pointing me in the right direction and for your great work on this app!  bill

**Comment by manabusakai** [comment]
That’s all right!
