### ISSUE TITLE
Can we stop AWS from further usage if it goes beyond (ex: 1000$) X amount

### ISSUE THREAD

**Issue by yallanki9160** [awslabs/git-secrets#169]

**Comment by plygrnd** [comment]
I'm afraid that this request is out of scope for `git-secrets`. AWS has published [documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html) about billing alerts using CloudWatch.
