### ISSUE TITLE
GitHub Secrets 

### ISSUE THREAD

**Issue by VikashKothary** [awslabs/git-secrets#170]
Would be in scope for the project to support GitHub Secrets API as a provider? I feel like there's a lot of value there. 

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by sparr** [comment]
Can you elaborate on the desired functionality?

I imagine you might mean for git-secrets to use a provider to query the github api to fetch your encrypted secrets, then check your code for those literal secrets?

**Comment by VikashKothary** [comment]
Yep :)

**Comment by sparr** [comment]
https://docs.github.com/en/rest/actions/secrets

While secrets can be used in Actions and Secrets Scanning directly within Github, it doesn't seem to be possible to fetch a decrypted secret for use outside of Github.

Do you have some mechanism in mind for implementing this?

**Comment by VikashKothary** [comment]
I did a quick google and it seems you're right. In which case, I can't see how this could be implemented.

See:
- https://github.com/orgs/community/discussions/26277
- https://github.com/cli/cli/discussions/3397

While I think it would've been valuable, since it's not possible, I'd be happy to close this ticket.
