### ISSUE TITLE
main branch

### ISSUE THREAD

**Issue by jamesbrink** [awslabs/git-secrets#174]
Let's get a main branch going if we could. this takes 2 minutes

https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by vladimir-poleh** [comment]
And this manual will update all forks, local clones, scripts on the CI/CD servers and other related stuff in the some miracle way?

**Comment by jamesbrink** [comment]
No not at all, just thought it would be great to get the convo started. 

I was going to use my existing pre commit hooks to catch such wording with this tool.. then I also realized I'm referencing the master branch in my pre commit hooks. 

I'm certainly not saying to blow away master and break everything so I apologize for being so vague initially
