### ISSUE TITLE
get secret --add existing regex pattern returns exit code 1

### ISSUE THREAD

**Issue by weymanf** [awslabs/git-secrets#24]
We have scripts to set up our machines. But whenever we run it a second time with git secrets, it will fail on adding the same pattern matcher.

Apparently running `git secret --add --global "<existing pattern>"` to a pattern already configured will return an exit code 1 thus causing our script to fail.

**Comment by mtdowling** [comment]
You could append ` || true` to the end of the line that calls `git secrets --add` to ignore failures.

**Comment by weymanf** [comment]
That is what I've done, but I'm afraid I might make a typo one day it will just silently fail.
