### ISSUE TITLE
Recursive scan is broken

### ISSUE THREAD

**Issue by chrisgilmerproj** [awslabs/git-secrets#27]
@mtdowling @michaelwittig 

See commit https://github.com/awslabs/git-secrets/commit/513af41279b5b06cf855a1d8ae344002d5cb8b11#diff-9bcd3f161947f1bdee06e4b12046cb65

I believe that the recursive function is now broken with the latest commit.  

There is a test that shows it should work called `Scan recursively`:

https://github.com/awslabs/git-secrets/blob/513af41279b5b06cf855a1d8ae344002d5cb8b11/test/git-secrets.bats#L75-L81

And a test named `-recursive can only be used with --scan`:

https://github.com/awslabs/git-secrets/blob/513af41279b5b06cf855a1d8ae344002d5cb8b11/test/git-secrets.bats#L297-L300

I think this is broken and should replace `--list` with `--scan` as I've done here:

```
@test "-recursive can only be used with --scan" {
  repo_run git-secrets --scan -r
  [ $status -eq 1 ]
}
```

But a new test was added to ensure this fails named `-recursive is mutual exclusive with --scan`:

https://github.com/awslabs/git-secrets/blob/513af41279b5b06cf855a1d8ae344002d5cb8b11/test/git-secrets.bats#L292-L295

Can you clarify that this was intended or fix the broken behavior?  Thank you very much.

**Comment by michaelwittig** [comment]
Correct me if I'm wrong:

`git-secrets --scan -r` (no file/path given!)

was not working. it always died with "-r|--recursive cannot be supplied with --cached, --no-index, or --untracked". The test [-recursive is mutual exclusive with --scan](https://github.com/awslabs/git-secrets/blob/master/test/git-secrets.bats#L292) makes sure that this works now. it checks for success rather than error. 

The test https://github.com/awslabs/git-secrets/blob/513af41279b5b06cf855a1d8ae344002d5cb8b11/test/git-secrets.bats#L297-L300 checks that --list can't be used with -r.

**Comment by chrisgilmerproj** [comment]
I actually can't get this to work in any format.  I'm also sorry, I don't have the historical context of whether or not this worked previously.

```sh
$  git secrets --scan -r
-r|--recursive cannot be supplied with --cached, --no-index, or --untracked
$  git secrets --scan -r .
-r|--recursive cannot be supplied with --cached, --no-index, or --untracked
$  git secrets --scan -r `pwd`
-r|--recursive cannot be supplied with --cached, --no-index, or --untracked
$  git secrets --scan -r /full/path/to/my/git/repo/
-r|--recursive cannot be supplied with --cached, --no-index, or --untracked
```

Is there a debug or verbose mode where I can give you more information on what's going on with the internal variables?

Also, we should probably rename the test `-recursive can only be used with --scan` to `--recursive can't be used with --list`.

I wasn't clear on how to use the test suite or I would have attempted to submit a patch for this.

**Comment by chrisgilmerproj** [comment]
I take it back, I just figured out how to run the tests with bats.  I'll see if I can't figure out what's going on.

**Comment by mtdowling** [comment]
This issue is now resolved, correct?

**Comment by chrisgilmerproj** [comment]
Yep! Thanks for the help.
