### ISSUE TITLE
Global hooks

### ISSUE THREAD

**Issue by jbrodley** [awslabs/git-secrets#31]
Any way to set this at a Global Level with Github Enterprise? Or does it have to be installed locally?

**Comment by mtdowling** [comment]
The hooks have to be installed on a per-repo basis, but Git does offer some tooling for this. You can look into using the `git init --template` functionality in your repositories. This StackOverflow post provide some more information on this: http://stackoverflow.com/a/1977655/151504

You could also take a look at another Git repo I created called git-rook that aims to make this process simpler: https://github.com/mtdowling/git-rook. 

Note that installing globally is a separate concern outside of the scope of git-secrets.
