### ISSUE TITLE
How do you disable it after installing for a project?

### ISSUE THREAD

**Issue by shigg1120** [awslabs/git-secrets#37]
This is a noobish question but, how do you disable it after installing for a project?

**Comment by johnt337** [comment]
I ran into this same issue when I first looked at it.

Its not clearly documented but one way would be is after unlocking the repo, delete the .git-crypt, .git-attributes entries and the .git/git-crypt files/folders. Then just commit the updates and it should be revoked.

**Comment by eshellman** [comment]
I have this problem too, and @johnt337 's suggestion doesn't help

**Comment by eshellman** [comment]
But here's the answer; this should be added to the documentation:
remove the git-secrets hook in:

> [repo]/.git/hooks/prepare-commit-msg
> [repo]/.git/hooks/commit-msg
> [repo]/.git/hooks/pre-commit

**Comment by johnt337** [comment]
@eshellman thanks, sorry I was thinking https://github.com/AGWA/git-crypt
My bad.
