### ISSUE TITLE
How to exclude a folder?

### ISSUE THREAD

**Issue by hopewise** [awslabs/git-secrets#39]
How would I exclude a folder in the scan?

**Comment by mtdowling** [comment]
You can add an "allowed" pattern that excludes specific directories via the regular expression. The lines scanned when filtering out allowed patterns is formatted as follows:

```
filename:line:text
```

Where filename is the matched file (e.g., `./foo/bar.txt`), line is a line number (e.g., `124`), and `text` is the line of the file that matched one of your prohibited patterns (e.g., "this is the text").

You can add an allowed pattern that can filter out directories and files using regular expressions. This will exclude all matches in "somedirectory/name":

```
git secrets --add --allowed '^\./somedirectory/name:.*'
```

**Comment by olbrew** [comment]
I'm a bit stuck here. I have a dependency in the `node_modules` directory which is causing a lot of false positives. However I change or update your example it doesn't work for me. Using your regex adapted to `^\./directory/relative/to/root:.*'` still gives errors in the specified directory.
Ideally I want to exclude all  *all* `node_modules` directories and all subdirectories occurring anywhere in my project. A simple regex such as `'*node_modules/*'` looks like it should do the job but it doesn't work either. Anyone an idea of how to solve this?

**Comment by dizzersee** [comment]
@olbrew Did you solve the issue?
