### ISSUE TITLE
Git Commit Message is always prohibited

### ISSUE THREAD

**Issue by barryaconway** [awslabs/git-secrets#42]
Running this tool and no matter the git commit message entered it is prevented from committing.
Rem'ing out the git hook for the commit-msg allows it to pass - post this action it picks up any AWS  Keys which is the primary objective.
Is this the correct behaviour?

**Comment by mtdowling** [comment]
What is the output you see when a commit if prohibited? Is a particular pattern detected in your message?

**Comment by mtdowling** [comment]
Any updates here? I wasn't able to reproduce this.
