### ISSUE TITLE
Carriage return breaks the load_patterns function in Windows 10 Bash

### ISSUE THREAD

**Issue by yoshutch** [awslabs/git-secrets#43]
I ran into an issue when trying to run git-secrets on a repo in the Windows 10 Bash (not git bash, but the dev linux bash console for Windows). When I run `git secrets --scan` it fails and doesn't even give an error. After some digging I found that in the load_patterns() function the resulting list of patterns has carriage returns instead of spaces. Just carriage returns. The carriage returns then break the `git grep` command without returning even an error. So then the pre-commit hook thinks it succeeded when in fact it never attempted the process.

I was able to get it to work by changing line 55 in git-secrets:
`echo "$result"`
to:
`echo "$result" | tr -d "\r"`

This seemed to work on both the Windows 10 Bash, as well as Git Bash (and even windows Command Line). 

Now, I'm not sure if this is more of an issue with Windows 10 Bash (probably is), but since it was a fairly simple code fix, I thought it'd be good to document this just in case anyone else might be testing the Windows 10 Bash.

**Comment by mtdowling** [comment]
Thanks for bringing this to our attention and investigating a fix! Would you be open to submitting a pull request with this fix?
