### ISSUE TITLE
Adding to GitHub Desktop for OSX

### ISSUE THREAD

**Issue by Skeyelab** [awslabs/git-secrets#46]
No issue, just a note.

If you installed this via homebrew and you use Github Desktop, you can add this like so:

```
cp /usr/local/bin/git-secrets /Applications/GitHub\ Desktop.app/Contents/Resources/git/bin/git-secrets
```

**Comment by mtdowling** [comment]
Thanks for leaving this note. As long as the script is somewhere on your PATH, git should pick it up. Maybe others will find this information useful if just adding to your path doesn't work.
