### ISSUE TITLE
Does the git-secrets executable need to be installed on all systems that clone from the git repo?

### ISSUE THREAD

**Issue by babineaum** [awslabs/git-secrets#47]
If i was to "install" git-secrets into a repo, push the changes up to my repo, then go to another machine and clone that repo, would I have to "brew install git-secrets" again? Or is it installing itself as a precommit hook that lives with the repo? thanks.

**Comment by mtdowling** [comment]
Yes, you need to install git-secrets and configure it for each repo. Git doesn't distribute hooks or git configuration when you checkout a repo.
