### ISSUE TITLE
Adding to global pattern not shown in config file

### ISSUE THREAD

**Issue by tclu82** [awslabs/git-secrets#51]
Hi,

`git secrets --add 'my_pattern1'`, my_pattern1 is shown in .git/config. However, `git secrets --add --global 'my_pattern2'` is not shown in .git/config. Where can I find global pattern? Thanks

**Comment by mtdowling** [comment]
You can edit the config file of the current repo using `git config -e`.

You can edit the *global* config file using `git config -e --global`.
