### ISSUE TITLE
Appending to allowed literal will pass the check

### ISSUE THREAD

**Issue by spinwang** [awslabs/git-secrets#53]
I ran the following to add `somethingsecret` as an allowed password in literal form: 
```bash
git secrets --add 'password\s*=\s*.+'
git secrets --add --allowed --literal 'somethingsecret'
```
But I found that `password=somethingsecret1`, will also pass the check.

**Comment by mtdowling** [comment]
This looks like it's working as intended.

Allowed patterns are evaluated *after* checking for prohibited patterns. git-secrets will first identify that "password=somethingsecret1" is prohibited. It will then pipe the matching grep output for that line to another grep that checks for allowed patterns. If any of the allowed patterns match, then the text that was found is ignore.

I don't know what you're trying to do, but one way to mitigate these kinds of situations is to be more specific with your allowed patterns.

**Comment by spinwang** [comment]
Hi, thanks for the quick reply. I would like to make sure that **ONLY** `somethingsecret` can be used as a password, not `somethingsecret1`. I tried 
```
git secrets --add 'password\s*=\s*.+'
git secrets --add --allowed '^somethingsecret$'
```
but this will reject `somethingsecret` as well.

**Comment by spinwang** [comment]
@mtdowling I think I misunderstood the syntax. Thanks!!
