### ISSUE TITLE
git secrets --clone

### ISSUE THREAD

**Issue by hyandell** [awslabs/git-secrets#55]
Hi Git Secrets folk.

It would be nice if I could do:
```
  git secrets --clone <clone url> <clone-args>
```
and that would clone, then install the hook, then add some configurable default list of rules.

**Comment by topherszucs** [comment]
Hi there mind if I fork in

**Comment by mtdowling** [comment]
I would assume this kind of command would automatically install git-secrets (e.g., git-secrets --install), but I don't know how it could automatically register patterns, exclusions, or providers without a template of some kind.

Git provides built-in support for templatizing a repo, including hooks. For example, you can create a template directory that includes hooks, preconfigured patterns, exclusions, and providers. You could do this as a one-time setup step:

```bash
TEMPLATE_DIR="~/.git/templates/git-secrets"

# Create a template .git directory.
mkdir -p $TEMPLATE_DIR

# Install git-secrets to the template
git-secrets --install $TEMPLATE_DIR

# Put any providers, allowed, and patterns in the config file.
cat << EOF > $TEMPLATE_DIR/config
[secrets]
	providers = git secrets --aws-provider
	allowed = AKIAIOSFODNN7EXAMPLE
	allowed = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
	patterns = (\"|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)(\"|')?\\s*(:|=>|=)\\s*(\"|')?[A-Za-z0-9/\\+=]{40}(\"|')?
	patterns = (\"|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?(\"|')?\\s*(:|=>|=)\\s*(\"|')?[0-9]{4}\\-?[0-9]{4}\\-?[0-9]{4}(\"|')?
EOF
```

*Note: The values present in the template config file are merged with other git configuration when initializing a repo.*

When you clone a repo, simply provide the directory of the template:

```
git clone <some_repo> --template ~/.git/templates/git-secrets
```

This clones the repo and copies over the contents of the template to the .git directory, installing git-secrets and your git-secrets configuration. This also means that you can create different templates for different repos by just changing out the template path.

**Comment by plygrnd** [comment]
Hen - going to close this for now. Please let me know if Michael's answer above suffices and/or answers your question.
