### ISSUE TITLE
"Argument list too long" error on some repos

### ISSUE THREAD

**Issue by rnhurt** [awslabs/git-secrets#6]
I'm getting the following error when scanning some repos:
```
/usr/local/bin/git-secrets: line 56: /usr/bin/grep: Argument list too long
```
I'm guessing that the repos in question are two large.  The two that fail have a size-pack of 205,724 and 106,999 (generated with this command: `git count-objects -v`)

**Comment by mtdowling** [comment]
I'm guessing this is the result of running `git secrets --scan` with no directory? When run with no directory, we set the path to each file in the repository to a variable and then pass that to grep. I'm guessing that is tripping up grep. We have another issue related to this behavior in at https://github.com/awslabs/git-secrets/issues/5. I think we could either iterate over the files and scan them individually, or use git-grep when scanning repository files. I'll need to do some research to see what's possible.

Thanks for reporting.

**Comment by rnhurt** [comment]
Nope, this happens with repos that are very, very large, with lots of directories and files.

**Comment by martinschneider** [comment]
Is there any resolution for this?

**Comment by 0x736E** [comment]
Confirmed behaviour when scanning [openssl](https://github.com/openssl/openssl) on OSX.


```shell
$ git clone https://github.com/openssl/openssl.git
$ cd openssl
$ git-secrets --scan-history
/opt/homebrew/bin/git-secrets: line 105: /usr/bin/git: Argument list too long
```
