### ISSUE TITLE
Not scanned except the first file

### ISSUE THREAD

**Issue by t13a** [awslabs/git-secrets#66]
-  Arch Linux
-  bash 4.4.012
-  git 2.16.1
-  git-secrets at master

Here is how to reproduce.

    $ echo harmless > some.crt
    $ echo forbidden > some.key # should be matched
    $ git add -A
    $ git secrets --scan some.crt some.key
    (cause no errors)

`pre-commit` hook has same problem, since the internal behavior is almost the same as this.

    $ git status
    On branch master
    Your branch is up to date with 'origin/master'.

    Changes to be committed:
      (use "git reset HEAD <file>..." to unstage)

	    new file:   some.crt
	    new file:   some.key

    $ git commit -m 'commit'
     2 files changed, 2 insertions(+)
     create mode 100644 some.crt
     create mode 100644 some.key
    (secret was committed)

I have fixed this problem so I will send a pull request soon.

P.S.
I have also passed `test/pre-commit-hook.bats` and found a small error. After this fix, all tests are passed successfully. But why did this fail while others are succeeded?

**Comment by t13a** [comment]
Hmmm, I failed some tests. I will check it after I get up tomorrow.
https://travis-ci.org/awslabs/git-secrets/builds/336661419

**Comment by t13a** [comment]
I'm not sure there are other environmental dependence problems, but I fixed one.
https://travis-ci.org/awslabs/git-secrets/builds/336837712

This part is serious, so I will report it when found.

**Comment by hyandell** [comment]
Confirmed, only running on the first file for me.

**Comment by rix0rrr** [comment]
This is still broken. Any chance of getting an update here?

**Comment by mtdowling** [comment]
Sorry for the delay. I've merged #67, so this is now resolved. Thanks for your contribution!

**Comment by t13a** [comment]
Never mind. I'm glad you came back! Thank you for merging.
