### ISSUE TITLE
Pattern Causes Invalid preceding regular Expression Error

### ISSUE THREAD

**Issue by markdenihan** [awslabs/git-secrets#75]
I'm trying to add a pattern for Basic Auth headers but they result in Invalid preceding regular expression errors
**Regex**
`(Basic\ )(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)`

**Adding it to .git/config and trying to scan**
```console
mark@mark-VirtualBox:~/git/gitsecrets-test$ git secrets --add '(Basic\ )(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)'
mark@mark-VirtualBox:~/git/gitsecrets-test$ cat .git/config | grep patterns
	patterns = (Basic\\ )(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)
mark@mark-VirtualBox:~/git/gitsecrets-test$ git secrets --scan
fatal: command line, '[A-Z0-9]{20}|("|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)("|')?\s*(:|=>|=)\s*("|')?[A-Za-z0-9/\+=]{40}("|')?|("|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?("|')?\s*(:|=>|=)\s*("|')?[0-9]{4}\-?[0-9]{4}\-?[0-9]{4}("|')?|(Basic\|)(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)': Invalid preceding regular expression
```
Any thoughts?

**Comment by markdenihan** [comment]
Was not using egrep syntax for pattern

`(Basic.)([[:alnum:]]{4})*([[:alnum:]]{2}+[=]{0,2})`

**Comment by markdenihan** [comment]
Wrong Regex Syntax. This works;
`(Basic )([[:alnum:]]{4})*([[:alnum:]]{2}+[=]{0,2})`

**Comment by rupsray** [comment]
@markdenihan I am also facing the same issue. My regex is:
(?=.*[A-Z])(?<![A-Za-z0-9\/+=])[A-Za-z0-9\/+=]{40}(?![A-Za-z0-9\/+=])

I validated this in www.rubular.com
Can you please tell me where can we convert or validate the type of regex supported by git-secrets?
