### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by greenrd** [awslabs/git-secrets#85]
There hasn't been a release for over 2 years. The current released version does not work on my Windows machine due to https://github.com/awslabs/git-secrets/pull/40 (which actually fixes an issue that is not OS-specific, but tends to affect Windows users more often) not being in the release. It would be nice to have a new release to make it easier for Windows users.

**Comment by KevinHock** [comment]
Hi @greenrd, there is https://github.com/Yelp/detect-secrets which is pretty active, it may be of interest to you.

**Comment by mtdowling** [comment]
Just tagged 1.3.0
