### ISSUE TITLE
feature request: uninstall

### ISSUE THREAD

**Issue by kalexmills** [awslabs/git-secrets#95]
Seems there is no way to undo all the stuff that this tool does to a repository.

Looks like I will have to do it manually. :-(

**Comment by kalexmills** [comment]
Specifically, I am getting the below error anytime I commit to a repository, even after I brew uninstall, and delete / re-clone the repository.

```
[alex.mills@L110615 iris-app 08:29:42]  git commit -a
git: 'secrets' is not a git command. See 'git --help'.
```

**Comment by kalexmills** [comment]
Looks like to resolve this, you can just do `rm -rf .git/hooks/*`

But this removes ALL githooks. It should only be used by the desperate or reckless, and it does not resolve the core problem this tool has.

**Comment by microbuilder** [comment]
I came here looking for the same thing, and you can manually disable this by editing the following three files, or deleting them if there is only the one entry in them:

- `.git/hooks/commit-msg`
- `.git/hooks/pre-commit`
- `.git/hooks/prepare-commit-msg`

**Comment by literakl** [comment]
This works for git hooks. But I cannot find, where a pattern configuration is stored:

git secrets --scan-history
cat: 'C:/bin/Git/path/to/secret/file/patterns': No such file or directory

**Comment by craigboman** [comment]
Although no `git secrets -r` command exists, go into your local top level git repo directory and `vi ~/.git/config`. In config you should see your git secrets near the bottom blocked together under [secrets]. Scroll down to the desired row and type d to delete that secret row, then escape saving your changes.

**Comment by LunarMother** [comment]
https://github.com/awslabs/git-secrets/issues/95?email_source=notifications&email_token=ACSMZRNDVDZ3RW3HOL5HKDLRDX4BRA5CNFSM4GGPLGHKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWYGERUA#event-3054258384 #Closed #95.

**Comment by azazi-sa** [comment]
+1 to a clean uninstall process.

Current manual process requires you to:
- delete `secrets` from .git/config for all local repositories
- delete `secrets` from .gitconfig
- remove `commit-msg`, `pre-commit` and `prepare-commit-msg` hooks from all git repositories
- change/remove git template so that it does not configure these hooks for newer repos.
- uninstall binary

This is too much manual work.

**Comment by chaitanyasurapaneni** [comment]
on top of, what @azazi-sa mentioned

You have to figure out where the binary is actually installed. 
Following are the multiple places you can look in the **Linux** based machine.

- By default all the git core command scripts are available in `/usr/lib/git-core/` directory.
- Apart from that, you can check in `/usr/bin/` and `/usr/local/bin/` directories as well.
- If you are still **NOT** able to find the binary, then type `which git-secrets` to identify the place where actually `git-secrets` is installed.

**Comment by vasanthaneppali** [comment]
> This works for git hooks. But I cannot find, where a pattern configuration is stored:
> 
> git secrets --scan-history cat: 'C:/bin/Git/path/to/secret/file/patterns': No such f
